language: python
os: linux
dist: xenial
python: 3.7

env:
  global:
      # Doctr deploy key for pcdshub/lcls-twincat-optics
      - secure: "lWQrdGr9GMk96tooHnPViOL+x+Qjg8vCrhBpMJxR585GX8sxH81PWcFOGcG4jMY3ZskEvg0bSwacvy3EunS9dnVcIB99qZ18J58ogXEMZkwTYC9cIqeT/r7FAd+IdcgYijB+dnzKzMcT7jExSPDez3rKlCcaT6QJB3XNWRvWFohugLtsAGnkSudbX6Jm8jTwwdN2ADlLfOJ9dGSEVA6cA0rxOyEwb2sUAPlRvaj+mrY0QWELGjoM/L6VsXBgSdjymiprqlTyGALmeENCPQSTYzWaKGuDnaxV8kuQcd8xzNnMepbDk2h7e3E4fupGj3P64CPoJHCB+/bUM9x6TVWme+iidewjOG5jvsrIHjO8PuSbky893SFIdy3kWUl6xBuEhM6TGHd2ebf3FgkJPacpsaAIC0786eKHgTaHwo4BXFRHi5G6N4ws49mp8PLl2v8sy//pYTDTQWvBBliyNw77d7sOq2luSVee5L+ONjd/oH8olWXFYD/q+f7gMwlcyaAQA+iLaTmgXZHf/gvnWRb9IaB+7mJGgjGPGWWZhuM6OPti0fuQ7sA1GPqQ0fzBnrBZSD2PxLI5i0w56YMZBCTxe9Hxi3cPY/rHfBDmASMhiKybaTX3pSn54APqPntmdmBSIOzySldqF8ICHUAJUwJrsYxklT01Qi7VOasBdrr+kV4="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    - TWINCAT_STYLE_EXCLUDE=tc_mca_std_lib

# Uncomment this block if you would like to make a test an allowed failure
#jobs:
#  allow_failures:
#    - name: "Python 3.6 - PIP"

import:
  - klauer/pcds-ci-helpers:travis/shared_configs/twincat/standard.yml
