version: ~> 1.0

env:
  global:
    # Doctr deploy key for **** NOTE **** klauer/lcls-twincat-optics
    - secure: "r4R/5EkAu1aNqFI03XINuq/gn9jZpZz23i1VhDHhu3SCxM+AcW2V+Gu5lu/qYNgrUnfKVATIRoEaBGoPA30fXDnhN/CVvWScPHGB6BoxJ/SYhqKD64zNbv0VVoNpn/Ko/jTpGE9fn2xK2h0TFOeNVxZfmUE13yLLMShxZhmNN/D19XNiVtEysIvG4t65NXh+ouS4T6hCWDEj5IZObeA28tQDYrl13LFzEacrcM6ocWkYXtU1+nCWCvgqkBwEXGav2qnV0Evcp+/RGmY0F1p/ZXpQX6YekDAWE6zrkUXrJAbiAvYP22cHlxUKtSSL3t3M/x98DhtfkFu01B9icOZuqANGV5+dmp7vmwdRqTdTWC9oYjdFF9rhyc/73/uSsUGwtZM6u/Lgt3LGzqoq1BJFVmpcBRzeey3GuOQX9ePltZQglsed+f7fGtkuZjqT51WFSHh9zDsknuNqszeeeOcvd7kG/3rIGjcrbE+dVQ6ploHSBbaga9DGlTZJemXDETNNeb4GNSa4AVi2bqYKffgY/MRCqNdnXhnP+7nvlcCdXiV5PQ8WZg2hgIhXbKhaDN+4XZGrXrhQ69DrDS5dAoJJ7FJW/XJJp//ykIL9Ke0qzdaItdWdBIKsa1VNg2+FKs23YDbEg+n57l7PYlL5qxYqLRcmQO6j71BpgLgzScejGvo="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"

# Uncomment this block if you would like to make a test an allowed failure
jobs:
  allow_failures:
    - name: "Style Check"
    - name: "Pre-commit Checks"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/standard.yml
